# Generated by Django 5.2.4 on 2025-08-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="student_member",
            new_name="student",
        ),
    ]
