# Generated by Django 5.2.4 on 2025-09-14 14:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_meeting_meetingattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(default=api.models.default_start_time),
        ),
    ]
