# Generated by Django 5.2.4 on 2025-08-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_lead_student_alter_student_user_alter_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("STUDENT", "student"), ("LEAD", "lead"), ("ADMIN", "admin")],
                max_length=10,
            ),
        ),
    ]
