# Generated by Django 5.2.4 on 2025-08-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="roll_no",
            field=models.CharField(default="", max_length=20),
        ),
    ]
