# Generated by Django 5.2.4 on 2025-09-20 20:12

import api.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_student_profile_desc_student_profile_pic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(upload_to=api.models.event_image_upload_path),
                ),
                ("content", models.TextField()),
                ("date", models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.TimeField(default="08:12 PM"),
        ),
    ]
