# Generated by Django 5.2.4 on 2025-09-21 16:42

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_event_alter_meeting_start_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.TimeField(default="04:42 PM"),
        ),
        migrations.CreateModel(
            name="EventImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="/opt/codehub-website/backend/media/events/default.png",
                        null=True,
                        upload_to=api.models.event_image_upload_path,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="api.event",
                    ),
                ),
            ],
        ),
    ]
