# Generated by Django 5.2.4 on 2025-10-03 19:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event_eventimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InlineImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.temp_inline_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, default='D:\\New folder (7)\\codehub-website\\backend\\media/events/default.png', null=True, upload_to=api.models.event_image_upload_path),
        ),
    ]
