# Generated by Django 5.2.4 on 2025-09-21 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_event_image_alter_meeting_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventimage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.event",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="start_time",
            field=models.TimeField(default="05:25 PM"),
        ),
    ]
